### ISSUE TITLE
Feature Request for User Configurable Module for DMR XLX connection

### ISSUE THREAD

**Issue by yngwiechou** [AndyTaylorTweet/Pi-Star_Binaries_sbin#7]
Hi Andy,

I created a separate issue since I know previously, the initial connection module for DMR to XLX server is configurable on pi-star web page. And it has been hard coded and moved to XLXHosts.txt.

The reason I made this request is:

To specify the module on XLX, we will need to connect to 4001 for Module A for example.
If we have the initial TG hard coded in XLXHosts.txt, it is not a problem for DMR device with a key pad.
However, for some DMR devices, for example, Motorola SL1M, they have no key pad.
In this case, it becomes inconvenient for people who have such non-keypad devices to manual dial in to switch Modules on XLX.

I guess your intention is to provide a simplest way for pi-star user to select XLX Master by selecting an item in the drop down list.
If that's the case, I think there might be another possibility.

If I recalled correctly, XLXd should have an API to list all the XLX servers as well as the number of modules enabled. Since XLX modules are always started with A, I think we just need to get the number of modules enabled, and create a drop down list for example A to F by javascript once user determined the XLX server from XLX Master drop down list.
With this approach, it might make it easier for DMR users with non-keypad devices.

Please feel free to let us know your thought.

Regards,
Yngwie Chou
BU2EA

**Comment by AndyTaylorTweet** [comment]
The old version of DMRGateway allowed the option to specify the module connected to on startup - the current version does not allow for this, now you can only select the startup XLX master, and the rest is driven from the radio (allowing you to move between XLX masters by calling 68nnn, where nnn is the number of the master), and swapping rooms by calling 640nn where nn is the number of the module / room.

This is an up-stream change from the DMRGateway developers.

In order to give you the ability to specify your own startup module/room, you can now create /root/XLXHosts.txt, put ONLY the host line with the modified room number in to this file - for example:

000;23.111.174.198;4001

On the next update this will over-ride XLX000's startup room to be 4001 and not 4004.

I hope this answers your question.

**Comment by yngwiechou** [comment]
Hi Andy,

Much appreciated for your explanation.
Understood that this is an upstream issue.

I'll try to get in touch with DMRGateway team to see if this is possible, since it will be a problem for non-keypad devices.

For example:

https://www.motorolasolutions.com/en_xp/products/mototrbo/portable-radios/sl1m.html#tabproductinfo

Thanks again!

Regards,
Yngwie
BU2EA
